import { computeFixFailureDirective } from '../bin/run-pipeline';

describe('computeFixFailureDirective', () => {
  const reproPath = 'tests/test_repro_issue_23.py';
  const module = 'python/instrumentation/openinference-instrumentation-smolagents/';

  test('returns undefined for empty retry context', () => {
    expect(computeFixFailureDirective('', reproPath, module)).toBeUndefined();
  });

  test('returns undefined for unrecognized failure shape', () => {
    expect(
      computeFixFailureDirective('Some other test failure unrelated to known retry patterns', reproPath, module)
    ).toBeUndefined();
  });

  test('protected_path: extracts repro path from message and surfaces affectedModule', () => {
    const ctx =
      'Fix agent attempted to modify the repro test (tests/test_repro_issue_23.py). The repro test is read-only...';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('tests/test_repro_issue_23.py');
    expect(d).toContain('READ-ONLY');
    expect(d).toContain(module);
    expect(d).toContain('DO NOT');
  });

  test('protected_path: falls back to provided reproTestPath when message does not include parens', () => {
    const ctx = 'Fix attempt threw: repro test is read-only — do not include it.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toContain(reproPath);
  });

  test('protected_path: uses placeholder when no path info is available', () => {
    const ctx = 'Fix attempt threw: repro test is read-only';
    const d = computeFixFailureDirective(ctx, undefined, module);
    expect(d).toBeDefined();
    expect(d).toContain('<the reproTest path>');
  });

  test('out_of_scope: highlights affectedModule', () => {
    const ctx = 'Fix attempt threw: Fix agent produced out-of-scope changes: docs/foo.md, scripts/bar.sh.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain(module);
    expect(d).toContain('out-of-scope');
  });

  test('destructive rewrite: tells LLM to re-emit full files', () => {
    const ctx = 'Fix attempt threw: detected destructive whole-file rewrite in:\n  - pkg/foo/bar.py: collapsed to ellipsis';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('COMPLETE');
    expect(d!.toLowerCase()).toContain('truncation');
  });

  test('empty-changes: redirects LLM to source-line targeting', () => {
    const ctx = 'No changes generated by fix agent';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d!.toLowerCase()).toContain('zero changes');
  });
});
