import { computeFixFailureDirective } from '../bin/run-pipeline';

describe('computeFixFailureDirective', () => {
  const reproPath = 'tests/test_repro_issue_23.py';
  const module = 'python/instrumentation/openinference-instrumentation-smolagents/';

  test('returns undefined for empty retry context', () => {
    expect(computeFixFailureDirective('', reproPath, module)).toBeUndefined();
  });

  test('returns undefined for unrecognized failure shape', () => {
    expect(
      computeFixFailureDirective('Some other test failure unrelated to known retry patterns', reproPath, module)
    ).toBeUndefined();
  });

  test('protected_path: extracts repro path from message and surfaces affectedModule', () => {
    const ctx =
      'Fix agent attempted to modify the repro test (tests/test_repro_issue_23.py). The repro test is read-only...';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('tests/test_repro_issue_23.py');
    expect(d).toContain('READ-ONLY');
    expect(d).toContain(module);
    expect(d).toContain('DO NOT');
  });

  test('protected_path: falls back to provided reproTestPath when message does not include parens', () => {
    const ctx = 'Fix attempt threw: repro test is read-only — do not include it.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toContain(reproPath);
  });

  test('protected_path: uses placeholder when no path info is available', () => {
    const ctx = 'Fix attempt threw: repro test is read-only';
    const d = computeFixFailureDirective(ctx, undefined, module);
    expect(d).toBeDefined();
    expect(d).toContain('<the reproTest path>');
  });

  test('out_of_scope: highlights affectedModule', () => {
    const ctx = 'Fix attempt threw: Fix agent produced out-of-scope changes: docs/foo.md, scripts/bar.sh.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain(module);
    expect(d).toContain('out-of-scope');
  });

  test('destructive rewrite: tells LLM to re-emit full files', () => {
    const ctx = 'Fix attempt threw: detected destructive whole-file rewrite in:\n  - pkg/foo/bar.py: collapsed to ellipsis';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('COMPLETE');
    expect(d!.toLowerCase()).toContain('truncation');
  });

  test('empty-changes: redirects LLM to source-line targeting', () => {
    const ctx = 'No changes generated by fix agent';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d!.toLowerCase()).toContain('zero changes');
  });

  test('eval-failed (NameError): surfaces missing import and forbids touching repro', () => {
    const ctx =
      `Eval failed: A sandbox command failed\n` +
      `Retry hints:\n` +
      `- python tests/test_repro_issue_23.py: Traceback (most recent call last):\n` +
      `  File ".../tests/test_repro_issue_23.py", line 29, in test_x\n` +
      `    _finalize_step_span(span, step_log)\n` +
      `  File ".../_wrappers.py", line 247, in _finalize_step_span\n` +
      `    if isinstance(span, NonRecordingSpan):\n` +
      `NameError: name 'NonRecordingSpan' is not defined`;
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('NonRecordingSpan');
    expect(d).toContain('did NOT import');
    expect(d).toContain('read-only');
    expect(d).toContain(reproPath);
  });

  test('eval-failed (ImportError): tells LLM to fix the import path, not the repro', () => {
    const ctx =
      `Eval failed: A sandbox command failed\n` +
      `Retry hints:\n` +
      `- python tests/test_repro_issue_23.py: ImportError: cannot import name 'Foo' from 'bar'`;
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('ImportError');
    expect(d).toContain('read-only');
    expect(d).toContain(reproPath);
  });

  test('eval-failed (generic): falls back to forbidding repro edits and surfacing sandbox output', () => {
    const ctx =
      `Eval failed: A sandbox command failed\n` +
      `Retry hints:\n` +
      `- pytest tests/: AssertionError: expected X got Y`;
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('still failed');
    expect(d).toContain('read-only');
    expect(d).toContain('AssertionError');
  });

  test('no_changes_to_commit: switches the LLM to sourcePatches mode', () => {
    const ctx = 'Fix attempt threw: No changes to commit — your content was BYTE-FOR-BYTE IDENTICAL to HEAD.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('sourcePatches');
    expect(d).toContain('oldText');
    expect(d).toContain('newText');
    expect(d).toContain(reproPath);
  });

  test('patch_not_found: tells the LLM to copy oldText byte-for-byte', () => {
    const ctx =
      'Fix attempt threw: Patch oldText for src/foo.py was not found in the file.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('src/foo.py');
    expect(d).toContain('byte-for-byte');
    expect(d).toContain('moduleSource');
  });

  test('patch_ambiguous: tells the LLM to expand oldText with more surrounding lines', () => {
    const ctx =
      'Fix attempt threw: Patch oldText for src/foo.py matched 3 times — it is ambiguous.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('src/foo.py');
    expect(d).toContain('3');
    expect(d).toContain('EXPAND');
  });

  test('patch_target_missing: tells the LLM to use action="create" for new files', () => {
    const ctx =
      'Fix attempt threw: Patch target src/missing.py could not be read from the branch: ENOENT.';
    const d = computeFixFailureDirective(ctx, reproPath, module);
    expect(d).toBeDefined();
    expect(d).toContain('src/missing.py');
    expect(d).toContain('action="create"');
  });
});
